package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

func helpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "guide",
		Short: "Show usage guide",
		Long:  "Show common cli workflows and examples",
		Run:   showUsageGuide,
	}
	return cmd
}

func showUsageGuide(cmd *cobra.Command, _ []string) {
	fmt.Println("cli Usage Guide")
	fmt.Println("==================")
	fmt.Println()

	fmt.Println("Global flag")
	fmt.Println()
	fmt.Println("  --rpc <url>   RPC endpoint for online commands")
	fmt.Println()

	fmt.Println("Proposal commands")
	fmt.Println()
	fmt.Println("  Create a validator proposal:")
	fmt.Println("    cli proposal create \\")
	fmt.Println("      -p 0xPROPOSER \\")
	fmt.Println("      -t 0xTARGET_VALIDATOR \\")
	fmt.Println("      -o add \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Create a config proposal:")
	fmt.Println("    cli proposal config \\")
	fmt.Println("      -p 0xPROPOSER \\")
	fmt.Println("      -i 0 \\")
	fmt.Println("      -v 86400 \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Vote on a proposal:")
	fmt.Println("    cli proposal vote \\")
	fmt.Println("      -s 0xVALIDATOR \\")
	fmt.Println("      -i PROPOSAL_ID \\")
	fmt.Println("      -a \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Query proposals:")
	fmt.Println("    cli proposal query -i PROPOSAL_ID --rpc https://rpc.example")
	fmt.Println("    cli proposal list --rpc https://rpc.example")
	fmt.Println("    cli proposal param -c 0 --rpc https://rpc.example")
	fmt.Println()

	fmt.Println("Validator commands")
	fmt.Println()
	fmt.Println("  List validators:")
	fmt.Println("    cli validator list --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Query validator details:")
	fmt.Println("    cli validator query -a 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Edit validator metadata:")
	fmt.Println("    cli validator edit \\")
	fmt.Println("      -v 0xVALIDATOR \\")
	fmt.Println("      -f 0xFEE_ADDRESS \\")
	fmt.Println("      -m my-validator \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Claim validator profits:")
	fmt.Println("    cli validator claim \\")
	fmt.Println("      -c 0xCALLER \\")
	fmt.Println("      -v 0xVALIDATOR \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()

	fmt.Println("Staking commands")
	fmt.Println()
	fmt.Println("  Register validator:")
	fmt.Println("    cli staking validator-register \\")
	fmt.Println("      -p 0xVALIDATOR \\")
	fmt.Println("      -s 100000 \\")
	fmt.Println("      -c 500 \\")
	fmt.Println("      --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Delegate and undelegate:")
	fmt.Println("    cli staking delegate -d 0xDELEGATOR -v 0xVALIDATOR -s 1000 --rpc https://rpc.example")
	fmt.Println("    cli staking undelegate -d 0xDELEGATOR -v 0xVALIDATOR -s 500 --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Rewards and delegation queries:")
	fmt.Println("    cli staking claim-rewards -c 0xDELEGATOR -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking claim-validator-rewards -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking query-delegation -d 0xDELEGATOR -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking query-unbonded -d 0xDELEGATOR -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  Validator stake management:")
	fmt.Println("    cli staking stake-increase -v 0xVALIDATOR -s 1000 --rpc https://rpc.example")
	fmt.Println("    cli staking stake-decrease -v 0xVALIDATOR -s 1000 --rpc https://rpc.example")
	fmt.Println("    cli staking set-commission -v 0xVALIDATOR -r 500 --rpc https://rpc.example")
	fmt.Println("    cli staking validator-deregister -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking validator-exit -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking validator-unjail -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println("    cli staking withdraw-unbonded -c 0xCLAIMER -v 0xVALIDATOR --rpc https://rpc.example")
	fmt.Println()

	fmt.Println("Offline signing workflow")
	fmt.Println()
	fmt.Println("  1. Generate an unsigned transaction:")
	fmt.Println("    cli proposal create -p 0xPROPOSER -t 0xTARGET_VALIDATOR -o add --rpc https://rpc.example")
	fmt.Println()
	fmt.Println("  2. Sign it offline:")
	fmt.Println("    cli misc sign -f data/createProposal.json -w /path/to/keystore -p /path/to/password.txt")
	fmt.Println("    cli misc sign -f data/createProposal.json -k <hex-private-key>")
	fmt.Println()
	fmt.Println("  3. Broadcast the signed transaction:")
	fmt.Println("    cli misc send -f data/createProposal_signed.json --rpc https://rpc.example")
	fmt.Println()

	fmt.Println("Online send workflow")
	fmt.Println()
	fmt.Println("  Send immediately with a keystore wallet:")
	fmt.Println("    cli proposal create \\")
	fmt.Println("      -p 0xPROPOSER \\")
	fmt.Println("      -t 0xTARGET_VALIDATOR \\")
	fmt.Println("      -o add \\")
	fmt.Println("      --rpc https://rpc.example \\")
	fmt.Println("      --send \\")
	fmt.Println("      --wallet /path/to/keystore \\")
	fmt.Println("      --password /path/to/password.txt")
	fmt.Println()
	fmt.Println("  Send immediately with a raw private key:")
	fmt.Println("    cli staking delegate \\")
	fmt.Println("      -d 0xDELEGATOR \\")
	fmt.Println("      -v 0xVALIDATOR \\")
	fmt.Println("      -s 1000 \\")
	fmt.Println("      --rpc https://rpc.example \\")
	fmt.Println("      --send \\")
	fmt.Println("      --private-key <hex-private-key>")
	fmt.Println()

	fmt.Println("Config ID reference")
	fmt.Println()
	fmt.Println("  0: proposalLastingPeriod")
	fmt.Println("  1: punishThreshold")
	fmt.Println("  2: removeThreshold")
	fmt.Println("  3: decreaseRate")
	fmt.Println("  4: withdrawProfitPeriod")
	fmt.Println("  5: blockReward")
	fmt.Println("  6: unbondingPeriod")
	fmt.Println("  7: validatorUnjailPeriod")
	fmt.Println("  8: minValidatorStake")
	fmt.Println("  9: maxValidators")
	fmt.Println("  10: minDelegation")
	fmt.Println("  11: minUndelegation")
	fmt.Println("  12: doubleSignSlashAmount")
	fmt.Println("  13: doubleSignRewardAmount")
	fmt.Println("  14: burnAddress")
	fmt.Println("  15: doubleSignWindow")
	fmt.Println("  16: commissionUpdateCooldown")
	fmt.Println("  17: baseRewardRatio")
	fmt.Println("  18: maxCommissionRate")
	fmt.Println("  19: proposalCooldown")
	fmt.Println()

	fmt.Println("More help")
	fmt.Println()
	fmt.Println("  cli --help")
	fmt.Println("  cli [command] --help")
	fmt.Println("  cli guide")
	fmt.Println()
}

func init() {
	rootCmd.AddCommand(helpCmd())
}
